"use client";

import type { TotoCombination } from "@/lib/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Target, ListOrdered, Info } from "lucide-react";

interface PredictionResultsDisplayProps {
  predictions: TotoCombination[];
  isLoading: boolean;
}

export function PredictionResultsDisplay({ predictions, isLoading }: PredictionResultsDisplayProps) {
  const getBallColor = (number: number): string => {
    if (number >= 1 && number <= 9) return "bg-red-500";
    if (number >= 10 && number <= 19) return "bg-blue-500";
    if (number >= 20 && number <= 29) return "bg-green-500";
    if (number >= 30 && number <= 39) return "bg-yellow-500 text-black";
    if (number >= 40 && number <= 49) return "bg-purple-500";
    return "bg-gray-500";
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Target className="h-6 w-6 text-primary" />
          AI Predictions
        </CardTitle>
        <CardDescription>
          Ranked TOTO number combinations generated by the AI. The first combination is considered the highest potential.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="flex flex-col items-center justify-center h-40">
            <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
            <p className="text-muted-foreground">Generating predictions, please wait...</p>
          </div>
        ) : predictions.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-40 text-center p-4 rounded-lg border border-dashed">
            <Info className="h-10 w-10 text-muted-foreground mb-3" />
            <p className="text-muted-foreground font-medium">No predictions available yet.</p>
            <p className="text-sm text-muted-foreground">Configure parameters and click "Generate Predictions".</p>
          </div>
        ) : (
          <ScrollArea className="h-[300px] rounded-md border">
            <ul className="p-4 space-y-3">
              {predictions.map((combination, index) => (
                <li
                  key={index}
                  className="flex items-center justify-between p-3 bg-card rounded-lg shadow-sm hover:shadow-md transition-shadow"
                >
                  <div className="flex items-center gap-2">
                    <Badge variant="secondary" className="w-8 h-8 flex items-center justify-center text-sm font-semibold">
                      {index + 1}
                    </Badge>
                    <div className="flex space-x-1.5">
                      {combination.map((num) => (
                        <span
                          key={num}
                          className={`flex items-center justify-center w-7 h-7 rounded-full text-xs font-bold text-white ${getBallColor(num)}`}
                        >
                          {num}
                        </span>
                      ))}
                    </div>
                  </div>
                  {/* Score can be added here if provided by AI later */}
                  {/* <Badge variant="outline">Score: N/A</Badge> */}
                </li>
              ))}
            </ul>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
}

// Helper component for loading state to be used in PredictionResultsDisplay
const Loader2 = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <path d="M21 12a9 9 0 1 1-6.219-8.56" />
  </svg>
);
