
"use client";

import Link from "next/link";
import { useState, useCallback, useEffect } from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Target, Loader2, AlertCircle, ListOrdered, PlayCircle, Info, TrendingUp, TrendingDown, Database } from "lucide-react";
import type { HistoricalResult, TotoCombination } from "@/lib/types";
import { OFFICIAL_PREDICTIONS_DRAW_ID, type HistoricalPerformanceDisplayData } from "@/lib/types";
import { NumberPickingToolDisplay } from "@/components/toto/NumberPickingToolDisplay";
import { FavoriteStarButton } from "@/components/toto/FavoriteStarButton";
import {
  getBallColor as getOfficialBallColor,
  formatDateToLocale,
} from "@/lib/totoUtils";
import { zhCN } from "date-fns/locale";
import {
  saveCurrentDrawToolPrediction,
  saveHistoricalToolPredictions,
  calculateSingleToolPrediction,
  calculateHistoricalPerformances,
  type ToolPredictionInput,
} from "@/lib/actions";

import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

interface SerializableTool {
  id: string;
  name: string;
  description: string;
}

interface ToolDetailPageClientProps {
  tool: SerializableTool;
  initialSavedPrediction: number[] | null; // This is the pre-fetched saved prediction for OFFICIAL_PREDICTIONS_DRAW_ID
  allHistoricalDataForPerformanceAnalysis: HistoricalResult[];
}


export function ToolDetailPageClient({
  tool: serializableTool,
  initialSavedPrediction,
  allHistoricalDataForPerformanceAnalysis,
}: ToolDetailPageClientProps) {
  const { user } = useAuth();
  const { toast } = useToast();

  const [savedPredictionForTargetDraw, setSavedPredictionForTargetDraw] = useState<number[] | null>(initialSavedPrediction);
  
  // State for predictions generated by admin click
  const [currentPredictionForSave, setCurrentPredictionForSave] = useState<number[] | null>(null);
  const [displayedHistoricalPerformances, setDisplayedHistoricalPerformances] = useState<HistoricalPerformanceDisplayData[] | null>(null);
  
  const [isLoadingAllPredictions, setIsLoadingAllPredictions] = useState(false); // Unified loader for admin "generate all"

  const isAdmin = user && user.email === "admin@totokit.com";
  const adminUID = user?.uid;

  useEffect(() => {
    // This effect primarily updates the display of the saved official prediction
    // if the initial prop changes (e.g., after an admin saves it).
    // It doesn't trigger new calculations on its own.
    setSavedPredictionForTargetDraw(initialSavedPrediction);
  }, [initialSavedPrediction]);


  const handleGenerateAllPredictions = async () => {
    if (!isAdmin || !adminUID) {
      toast({ title: "权限不足", description: "只有管理员才能执行此操作。", variant: "destructive" });
      return;
    }
    if (!allHistoricalDataForPerformanceAnalysis || allHistoricalDataForPerformanceAnalysis.length === 0) {
      toast({ title: "数据不足", description: "没有足够的历史数据来进行预测和回测。", variant: "destructive" });
      return;
    }

    setIsLoadingAllPredictions(true);
    setCurrentPredictionForSave(null); // Clear previous generated current prediction
    setDisplayedHistoricalPerformances(null); // Clear previous historical performances
    toast({ title: "处理中", description: `正在为工具 ${serializableTool.name} 生成当期及历史回测预测...` });

    try {
      const latestTenHistoricalDataForCurrentPred = allHistoricalDataForPerformanceAnalysis.slice(0, 10);

      const [singleToolPredictionResult, historicalPerfResult] = await Promise.all([
        calculateSingleToolPrediction(serializableTool.id, latestTenHistoricalDataForCurrentPred),
        calculateHistoricalPerformances(serializableTool.id, allHistoricalDataForPerformanceAnalysis)
      ]);

      // Update state with generated predictions
      if (singleToolPredictionResult) {
        setCurrentPredictionForSave(singleToolPredictionResult);
      } else {
         toast({ title: "当期预测生成失败", description: `工具 ${serializableTool.name} 未能为期号 ${OFFICIAL_PREDICTIONS_DRAW_ID} 生成预测。`, variant: "destructive" });
      }

      if (historicalPerfResult) {
        setDisplayedHistoricalPerformances(historicalPerfResult.length > 0 ? historicalPerfResult : []);
         if (historicalPerfResult.length === 0) {
            toast({ title: "历史回测", description: "历史表现分析未产生任何预测数据。" });
         }
      } else {
        setDisplayedHistoricalPerformances([]); // Ensure it's an empty array if null
        toast({ title: "历史回测生成失败", description: "历史表现分析未能执行或返回结果。", variant: "destructive" });
      }
      
      // Automatically save the generated predictions
      let currentSaveSuccess = false;
      let historicalSaveSuccess = false;
      let currentSaveMessage = "";
      let historicalSaveMessage = "";

      if (singleToolPredictionResult && singleToolPredictionResult.length > 0) {
        const currentPredictionData: ToolPredictionInput = {
          toolId: serializableTool.id,
          toolName: serializableTool.name,
          targetDrawNumber: OFFICIAL_PREDICTIONS_DRAW_ID,
          targetDrawDate: "PENDING_DRAW", // Or a more dynamic date if available
          predictedNumbers: singleToolPredictionResult,
          userId: adminUID,
        };
        const saveCurrentResult = await saveCurrentDrawToolPrediction(currentPredictionData);
        if (saveCurrentResult.success) {
          currentSaveSuccess = true;
          currentSaveMessage = saveCurrentResult.message || `期号 ${OFFICIAL_PREDICTIONS_DRAW_ID} 的预测已成功保存/更新。`;
          setSavedPredictionForTargetDraw(singleToolPredictionResult); // Update display of saved official prediction
        } else {
          currentSaveMessage = saveCurrentResult.message || "无法保存当期预测。";
        }
      } else {
        currentSaveMessage = `工具 ${serializableTool.name} 未能生成或生成了空的期号 ${OFFICIAL_PREDICTIONS_DRAW_ID} 预测，未保存。`;
      }

      if (historicalPerfResult && historicalPerfResult.length > 0) {
        const predictionsToSaveForDb: ToolPredictionInput[] = historicalPerfResult.map(hp => ({
          toolId: serializableTool.id,
          toolName: serializableTool.name,
          targetDrawNumber: hp.targetDraw.drawNumber,
          targetDrawDate: hp.targetDraw.date,
          predictedNumbers: hp.predictedNumbersForTargetDraw,
          userId: adminUID,
        }));

        if (predictionsToSaveForDb.length > 0) {
          const saveHistoricalResult = await saveHistoricalToolPredictions(
            serializableTool.id,
            serializableTool.name,
            predictionsToSaveForDb,
            adminUID
          );
          if (saveHistoricalResult.success) {
            historicalSaveSuccess = true;
            historicalSaveMessage = saveHistoricalResult.message || `已成功保存/更新 ${saveHistoricalResult.savedCount || 0} 条历史回测预测。`;
          } else {
            historicalSaveMessage = saveHistoricalResult.message || "无法批量保存历史回测预测。";
          }
        } else {
          historicalSaveMessage = "没有从历史表现中生成可保存的预测数据。";
        }
      } else {
        historicalSaveMessage = "历史表现分析未产生任何预测数据，未保存。";
      }

      if (currentSaveSuccess && historicalSaveSuccess) {
        toast({ title: "全面预测已生成并保存", description: `${currentSaveMessage} ${historicalSaveMessage}` });
      } else {
        toast({
          title: "预测处理部分完成",
          description: `当期预测: ${currentSaveMessage} 历史回测: ${historicalSaveMessage}`,
          variant: (currentSaveSuccess || historicalSaveSuccess) ? "default" : "destructive",
          duration: 8000,
        });
      }

    } catch (error: any) {
      toast({ title: "预测生成或保存出错", description: error.message || "处理预测时发生未知错误。", variant: "destructive" });
      setCurrentPredictionForSave(null);
      setDisplayedHistoricalPerformances([]);
    } finally {
      setIsLoadingAllPredictions(false);
    }
  };


  const OfficialDrawDisplay = ({ draw }: { draw: HistoricalResult }) => (
    <div className="flex flex-wrap gap-1.5 items-center">
      {draw.numbers.map((num) => (
        <Badge
          key={`official-${draw.drawNumber}-main-${num}`}
          className={`flex items-center justify-center w-7 h-7 rounded-full text-xs font-semibold shadow-sm ${getOfficialBallColor(num, false)}`}
        >
          {num}
        </Badge>
      ))}
      <span className="mx-1 text-muted-foreground">+</span>
      <Badge
        className={`flex items-center justify-center w-7 h-7 rounded-full text-xs font-semibold shadow-sm ${getOfficialBallColor(draw.additionalNumber, true)}`}
      >
        {draw.additionalNumber}
      </Badge>
    </div>
  );

  return (
    <div className="container mx-auto px-4 py-8 md:px-6 md:py-12">
      <div className="mb-6">
        <Button asChild variant="outline" size="sm">
          <Link href="/number-picking-tools">
            <ArrowLeft className="mr-2 h-4 w-4" />
            返回工具列表
          </Link>
        </Button>
      </div>

      <Card className="w-full">
        <CardHeader>
          <div className="flex justify-between items-start">
            <CardTitle className="flex items-center gap-2 text-xl">
              {serializableTool.name}
            </CardTitle>
            {user && <FavoriteStarButton toolId={serializableTool.id} toolName={serializableTool.name} />}
          </div>
          <CardDescription>{serializableTool.description}</CardDescription>
        </CardHeader>
        <CardContent>
          {/* Section for Current/Official Draw Prediction */}
          <div className="mb-6 pb-6 border-b">
            <h4 className="text-md font-semibold mb-2 flex items-center gap-1.5">
              <Target className="h-5 w-5 text-primary" />
              期号 {OFFICIAL_PREDICTIONS_DRAW_ID} 预测号码:
            </h4>
            {/* Display saved official prediction if available */}
            {savedPredictionForTargetDraw && savedPredictionForTargetDraw.length > 0 && (
              <>
                <p className="text-xs text-muted-foreground mb-1">已保存的预测 (来自数据库):</p>
                <NumberPickingToolDisplay numbers={savedPredictionForTargetDraw} />
              </>
            )}

            {/* Display admin-generated current prediction if available and different from saved */}
            {isAdmin && currentPredictionForSave && currentPredictionForSave.length > 0 &&
             JSON.stringify(currentPredictionForSave) !== JSON.stringify(savedPredictionForTargetDraw) && (
              <div className="mt-3">
                <p className="text-xs text-muted-foreground mb-1 text-amber-600">
                  新生成的预测 (点击“开始全面预测”生成, 待保存):
                </p>
                <NumberPickingToolDisplay numbers={currentPredictionForSave} />
              </div>
            )}
            
            {/* Message if no saved official prediction and user is not admin */}
            {!savedPredictionForTargetDraw && !isAdmin && (
               <Alert variant="default" className="mt-3">
                <Info className="h-4 w-4" />
                <AlertTitle>提示</AlertTitle>
                <AlertDescription>
                  期号 {OFFICIAL_PREDICTIONS_DRAW_ID} 的预测号码尚未由管理员生成。
                </AlertDescription>
              </Alert>
            )}
            
            {/* Message for admin if no saved or generated current prediction yet */}
            {isAdmin && !savedPredictionForTargetDraw && !currentPredictionForSave && !isLoadingAllPredictions && (
              <p className="text-sm text-muted-foreground mt-2 italic">
                点击下方“开始全面预测”按钮来生成期号 {OFFICIAL_PREDICTIONS_DRAW_ID} 的预测。
              </p>
            )}
          </div>

          {/* Admin Actions */}
          {isAdmin && (
            <div className="mb-6 pb-4 border-b">
              <Button onClick={handleGenerateAllPredictions} disabled={isLoadingAllPredictions || !allHistoricalDataForPerformanceAnalysis || allHistoricalDataForPerformanceAnalysis.length === 0} className="w-full">
                {isLoadingAllPredictions ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <PlayCircle className="mr-2 h-4 w-4" />
                )}
                开始全面预测 (当期及历史回测)
              </Button>
              {isLoadingAllPredictions && (
                <p className="text-center text-sm text-muted-foreground mt-2">
                  正在生成及保存预测数据... 请稍候...
                </p>
              )}
               {(!allHistoricalDataForPerformanceAnalysis || allHistoricalDataForPerformanceAnalysis.length === 0) && (
                 <p className="text-xs text-red-500 text-center mt-1">无法进行预测，因历史数据不足。</p>
               )}
            </div>
          )}

          {/* Section for Historical Performance */}
          {(isLoadingAllPredictions || displayedHistoricalPerformances !== null) && (
             <div className="pt-0"> {/* Changed from pt-4 to pt-0 */}
                <h4 className="text-md font-semibold mb-3 flex items-center gap-1.5">
                  <ListOrdered className="h-5 w-5 text-primary" />
                  历史开奖动态预测表现 (全部期数):
                </h4>
                {isLoadingAllPredictions && displayedHistoricalPerformances === null && ( 
                  <div className="flex items-center justify-center py-8">
                    <Loader2 className="h-8 w-8 animate-spin text-primary" />
                    <p className="ml-2 text-muted-foreground">加载历史表现数据...</p>
                  </div>
                )}
                {displayedHistoricalPerformances && displayedHistoricalPerformances.length > 0 && (
                  <ScrollArea className="h-[500px] rounded-md border p-3 space-y-4 bg-background/50">
                    {displayedHistoricalPerformances.map((performance) => {
                        if (!performance || !performance.targetDraw) return null; // Basic check
                        const { targetDraw, predictedNumbersForTargetDraw, hitDetails, hitRate, hasAnyHit, predictionBasisDraws } = performance;
                        return (
                        <div
                            key={`${serializableTool.id}-${targetDraw.drawNumber}`}
                            className={`p-3 border rounded-lg ${
                            hasAnyHit
                                ? "border-green-500/60 bg-green-500/10"
                                : "border-border bg-card"
                            }`}
                        >
                            <div className="flex justify-between items-center mb-1.5">
                            <p className="text-xs font-medium">
                                目标期号:{" "}
                                <span className="font-semibold text-primary">
                                {targetDraw.drawNumber}
                                </span>{" "}
                                ({formatDateToLocale(targetDraw.date, zhCN)})
                            </p>
                            {predictedNumbersForTargetDraw.length > 0 &&
                                (hasAnyHit ? (
                                <TrendingUp className="h-4 w-4 text-green-600" />
                                ) : (
                                <TrendingDown className="h-4 w-4 text-red-500/80" />
                                ))}
                            </div>
                            {predictionBasisDraws && (
                                <p className="text-xs text-muted-foreground italic mb-1">
                                    {predictionBasisDraws}
                                </p>
                            )}
                            <div className="mb-1.5">
                            <p className="text-xs text-muted-foreground mb-0.5">
                                当期开奖号码:
                            </p>
                            <OfficialDrawDisplay draw={targetDraw} />
                            </div>
                            <div className="mb-1.5">
                            <p className="text-xs text-muted-foreground mb-0.5">
                                工具针对本期预测号码 ({predictedNumbersForTargetDraw.length}{" "}
                                个):
                            </p>
                            {predictedNumbersForTargetDraw.length > 0 ? (
                                <NumberPickingToolDisplay
                                numbers={predictedNumbersForTargetDraw}
                                historicalResultForHighlight={targetDraw}
                                />
                            ) : (
                                <p className="text-xs text-muted-foreground italic">
                                数据不足或算法未生成预测
                                </p>
                            )}
                            </div>
                            {predictedNumbersForTargetDraw.length > 0 && hitDetails && (
                            <div className="text-xs space-y-0.5 text-foreground/90">
                                <p>
                                命中正码:{" "}
                                <span className="font-semibold">
                                    {hitDetails.mainHitCount}
                                </span>{" "}
                                个
                                {hitDetails.matchedMainNumbers.length > 0
                                    ? ` (${hitDetails.matchedMainNumbers.join(", ")})`
                                    : ""}
                                </p>
                                <p>
                                特别号码 ({targetDraw.additionalNumber}):{" "}
                                {hitDetails.matchedAdditionalNumberDetails?.matched ? ( // Optional chaining
                                    <span className="font-semibold text-yellow-600">
                                    命中
                                    </span>
                                ) : (
                                    <span className="text-muted-foreground">
                                    未命中
                                    </span>
                                )}
                                </p>
                                <p>
                                正码命中率 (对比工具预测数量):{" "}
                                <span className="font-semibold">
                                    {hitRate !== undefined ? hitRate.toFixed(1) : 'N/A'}%
                                </span>
                                </p>
                            </div>
                            )}
                        </div>
                        );
                    })}
                    </ScrollArea>
                )}
                {displayedHistoricalPerformances && displayedHistoricalPerformances.length === 0 && !isLoadingAllPredictions && (
                    <Alert variant="default" className="mt-3">
                        <Info className="h-4 w-4" />
                        <AlertTitle>无历史表现数据</AlertTitle>
                        <AlertDescription>
                          未能计算历史表现，可能是数据库中开奖数据不足 (少于11期) 或工具未生成预测。
                          {isAdmin && " 请确保数据库中至少有11期历史开奖数据。"}
                        </AlertDescription>
                    </Alert>
                   )
                }
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

    